services:
  jarvis:
    build: .
    container_name: jarvis
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./user/data/memory.db:/app/user/data/memory.db
      - ./src/tokens/google-oauth.json:/app/src/tokens/google-oauth.json
      - ./src/tokens/google-token.json:/app/src/tokens/google-token.json
      - ./src/tokens/firebase.json:/app/src/tokens/firebase.json
